### PR TITLE
Proxy support when fetching remote files

### PR DESCRIPTION
**Pull request by vitorbrandao**
This PR gives support for networks behind a proxy.

Proxy support is accomplished by setting a stream context to the `file_get_contents()` call.

Usage:

```
$browscap = new Browscap('/tmp');

// auto-detect proxy settings from the environment
$browscap->autodetectProxySettings();

// or, set proxy settings manually
$browscap->addProxySettings('proxy.example.com, 3128, 'http', 'myuser', 'mypass');

// check defined stream context options
$options = $browscap->getStreamContextOptions();

// remove proxy settings
$browscap->clearProxySettings()
```

Also, some phpunit tests are added as well as a travis config file for automatic testing on travis servers.

### CODE REVIEW

**Comment by GaretJax** [comment]
Exceptional! Great pull request, thank you noisebleed

**Comment by vitorbrandao** [comment]
No problem. I just love your project, very helpful. Thanks ;)

You'll need a travis service hook to "light up" your new shiny travis button. See > [here](http://about.travis-ci.org/docs/user/how-to-setup-and-trigger-the-hook-manually/) < how to do it.

**Comment by GaretJax** [comment]
Done... I guess we'll have to wait now ;)

(so the mail about a failing test I got today was because of you :D )

**Comment by vitorbrandao** [comment]
Yep, sorry about that!

You can push the `Test Hook` button in the [admin/travis](https://github.com/GaretJax/phpbrowscap/admin/hooks) page to trigger the build manually. Afterwards, on every push, the repo is automatically tested and the build status updated. The travis logo reflects the status of the `master` branch.

You may disable email notifications if you want.

**Pull request merged**
